// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4_BROKdz4onP9wndge18MIIxQnbK_2k',
    appId: '1:1011672755179:web:55b9209623ea7fd26947ae',
    messagingSenderId: '1011672755179',
    projectId: 'my-portfolio-47aa7',
    authDomain: 'my-portfolio-47aa7.firebaseapp.com',
    storageBucket: 'my-portfolio-47aa7.firebasestorage.app',
    measurementId: 'G-KCSJFGKVCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ClSF4I4fitfEA_quKB9wtK6kV3oweOA',
    appId: '1:1011672755179:android:aaa62a58c9578efb6947ae',
    messagingSenderId: '1011672755179',
    projectId: 'my-portfolio-47aa7',
    storageBucket: 'my-portfolio-47aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGGygky7OPAhh3JbwCctlV_IJutXnZWI',
    appId: '1:1011672755179:ios:301801f94d5da1c16947ae',
    messagingSenderId: '1011672755179',
    projectId: 'my-portfolio-47aa7',
    storageBucket: 'my-portfolio-47aa7.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );
}
